Update sonarQubescript

diff --git a/sonarQubescript b/sonarQubescript
--- a/sonarQubescript
+++ b/sonarQubescript
@@ -31,9 +31,9 @@ else
 fi	
 
 echo " Installing Mysql rpm Package "
-#cd /tmp/
-rpm -ivh cd /tmp/mysql-community-release-el7-5.noarch.rpm  &>>$LOG
-yum install  mysql-community-server -y 
+cd /tmp/
+rpm -ivh mysql-community-release-el7-5.noarch.rpm  &>>$LOG
+yum install  mysql-community-server -y  &>>$LOG
 
 if [ $? -ne 0 ] ; then
    echo " Installing Mysql rpm Package ... Failed "
@@ -82,7 +82,8 @@ else
 fi
 
 echo " Extracting Soanrqube package"
-unzip /tmp/sonarqube-6.7.6.zip  &>>$LOG
+unzip -o /tmp/sonarqube-6.7.6.zip  &>>$LOG
+mv sonarqube-6.7.6 /opt/sonarqube
 chown sonarqube. /opt/sonarqube -R
 if [ $? -ne 0 ] ; then
    echo " Extracting Soanrqube package ... Failed "
@@ -108,3 +109,14 @@ sonar.jdbc.url=jdbc:mysql://localhost:3306/sonarqube_db?useUnicode=true&amp;char
 #    sonar.jdbc.password=password
 #   sonar.jdbc.url=jdbc:mysql://localhost:3306/sonarqube_db?useUnicode=true&amp;characterEncoding=utf8&amp;rewriteBatchedStatements=true&amp;useConfigs=maxPerformance' > /opt/sonarqube/conf/sonar.properties
 #fi
+
+echo " Updating Sonarqude sonar.sh file "
+sed -i 's/#RUN_AS_USER=/RUN_AS_USER=sonarqube/g' /opt/sonarqube/bin/linux-x86-64/sonar.sh
+
+if [ $? -ne 0 ] ; then
+   echo " Updating Sonarqude sonar.sh file ... Failed "
+else
+   echo " Updating Sonarqude sonar.sh file ... Success"
+fi
+
+sh /opt/sonarqube/bin/linux-x86-64/sonar.sh start 
